CPSolver Fix
- new build of the CPSolver (same version, as of October 17)
- this fixes the NoSuchMethodError: GroupConstraint.getType()
  (caused by using a continous build)


Former-commit-id: a0ec03aaf06098ab15ebb6eec20be325b988b8e4