CPSolver Fix
- new build of the CPSolver (same version, as of September 25)
- this fixes the NoSuchMethodError: GroupConstraint.getType()
  (caused by using a continous build)


Former-commit-id: 547011bdcf78da5f0c668ba67d76be14908d4750