Solver Info: Value
- to avoid serialization issues with org.dom4j.Document class, the data are kept internally as a byte array and only converted to/from org.dom4j.Document when needed
  - this is used for instance when conflicting assignments are returned (introduced in commit de024bc)
  - this fixes the "java.lang.NoClassDefFoundError: org/jaxen/VariableContext" error on the Class Detail page


Former-commit-id: 8851f0f2d30bd6f182fb03be7c58dbf915bf6883